services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB_URI: ${POSTGRES_DB_URI}
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASSWD: ${POSTGRES_DB_PASSWD}

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend